---
title: "ProcessDataV2"
author: "LPersad"
date: "2024-01-26"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(dplyr)
library(tidyr)
# library(openxlsx)
# library(ggplot2)
# library(plotly)
library(ggpubr)
library(RColorBrewer)
# library(rcartocolor)
library(cowplot)
library(stringr)
# library(webr)
#read muscle information table
# library(gt)
library(jsonlite)
library("grid")
# library("gt")
library("flextable")

# library(esquisse)
# esquisser(data_r)

```

## Import and clean data

```{r load}
# Utility Functions
saveFig <- function(fig,name,wdth,hght){
  # Save final image
  savename <- paste(name,".png",sep = '')
  ggsave(filename = savename,
       plot = fig,
       width = wdth,
       height = hght,
       units = "in",
       dpi = 300)
  
}


corrections <- function(df){
  #this functions removes studies and rows 
  
  # Remove rows based on IDs
df <- subset(df, !(CovidenceID == 4184))
df <- subset(df, !(CovidenceID == 2679))
  # Remove rows where ID is 2837 and CSA is 'ACSA'
df <- subset(df, !(CovidenceID == 2837 & CSA == 'ACSA'))
df <- subset(df, !(CovidenceID == 2995 & CSA == 'ACSA'))

return (df)
}

#<---------------load and process paperstats - paperstats_r, paperstats_r_filtered

loadPaperStats <- function(){
  paperstats <- read.csv("./included/Paperstats.csv")
  #remove mistakes
  paperstats=corrections(paperstats)
  
  # Select specific columns and rename them
  paperstats_r <- paperstats %>%
  select(CovidenceID = CovidenceID, aveAge = "aveAge..years.",aveHeight = "aveHeight..cm.",
         aveWeight="aveWeight..kg.",N="X.Number.of.subjects..N",Muscle=Muscle,Type=Type,
         Gender=Gender,CSA=CSA,Miscellaneous=Miscellaneous,volORstim="Voluntary..V..or.Stimulated..S..Force.measurement",
         combineTitle="Title_x", studyID="Study.ID", country="Country", studyDesign="Study.design", year="Year",
         journal="Journal",aveST="aveST..N.cm2.",musclename="name")
  
  # colnames(paperstats)
  
  paperstats_r$journal <- as.factor(paperstats_r$journal)
  paperstats_r$musclename <- as.factor(paperstats_r$musclename)
  
  
  paperstats_r <- paperstats_r %>% drop_na(aveST) # remove muscles that had no ST vals
  paperstats_r <- paperstats_r[!paperstats_r$Muscle == '', ] # remove empty muscle rows
  levels(paperstats_r$journal)[levels(paperstats_r$journal) == "J Appl Physiol (1985)"] <- "J Appl Physiol" # rename this journal
  levels(paperstats_r$journal)[levels(paperstats_r$journal) == "GNB"] <- "GNB2012 Conference" # rename this journal
  levels(paperstats_r$journal)[levels(paperstats_r$journal) == "Journal of Applied Physiology"] <- "J Appl Physiol" # rename this journal
  levels(paperstats_r$journal)[levels(paperstats_r$journal) == "The journal of physiology"] <- "J Physiol" # rename this journal
  
  levels(paperstats_r$country)[levels(paperstats_r$country) == "UK"] <- "United Kingdom"
  
  
  #remove repeated to get proper paperstats
  paperstats_r_filtered <- paperstats_r %>% distinct(`CovidenceID`, `Muscle`, .keep_all = TRUE)
  
  # colnames(paperstats_r)
  
  output<-list(paperstats_r,paperstats_r_filtered)
  return(output)

}

# convert to just using one doc
# test <- read_excel("./included/ST_review_ALLdata_Lomas_processed.csv", sheet = "Plotdata")


#<---------------nowload and process plotdata - data_r

loadPlotdata <- function(){
  data <- read.csv("./included/Plotdata_scored.csv")
  

  #remove mistakes
  data=corrections(data)
  
  # Select specific columns and rename them
  data_r <- data %>%
  select(CovidenceID = CovidenceID, aveAge = "aveAge..years.",aveHeight = "aveHeight..cm.",
         aveWeight="aveWeight..kg.",N="X.Number.of.subjects..N",Muscle=Muscle,Type=Type,
         Gender=Gender,CSA=CSA,Miscellaneous=Miscellaneous,aveVol="aveVol..cm3.",
         aveFL="aveFL..cm.",avePCSA="avePCSA..cm2.",aveTorque="aveTorque..Nm.",
         aveForce="aveForce..N.",aveST="aveST..N.cm2.", agetype="Age.type", trainingtype="Training.type", muscleName="name",
         jointType="Joint.type", grav="antigrav.grav", jointAction="Joint.action", anatomicalLocation="anatomical.location", FastSlow="fast.slow", Type1="X.MHC.1_mean", Type2A="X.MHC.2A_mean", Type2X="X.MHC.2X_mean", Score="Score",mv_method="Muscle.volume.method",fl_method="Fascicle.length.method",pa_method="Pennation.angle.method",t_method="Torque.method", ma_method="Moment.arm.method", pcsa_method="PCSA.method", f_method="Force.method",newScore, studyID="Study.ID")
  
  data_r <- data_r %>% drop_na(aveST) # remove muscles that had no ST vals
  # Define the order you want for the legend
  desired_order <- c("CHD", "YNG", "MID", "OLD")
  
  
  # Convert to factors
  data_r$Gender <- as.factor(data_r$Gender)
  data_r$Muscle <- as.factor(data_r$Muscle)
  data_r$agetype <- factor(data_r$agetype, levels = desired_order)
  data_r$trainingtype <- as.factor(data_r$trainingtype)
  data_r$muscleName <- as.factor(data_r$muscleName)
  data_r$jointType <- as.factor(data_r$jointType)
  data_r$jointAction <- as.factor(data_r$jointAction)
  data_r$anatomicalLocation <- as.factor(data_r$anatomicalLocation)
  
  # # Returns string without leading white space
  # trim.leading <- function (x)  sub("^\\s+", "", x)
  # 
  # # Returns string without trailing white space
  # trim.trailing <- function (x) sub("\\s+$", "", x)
  # 
  # # Returns string without leading or trailing white space
  # trim <- function (x) gsub("^\\s+|\\s+$", "", x)
  # 
  # data_r$Gender <- trim(data_r$Gender)
  
  
  levels(data_r$agetype)[levels(data_r$agetype) == "CHD"] <- "Child (<18)" 
  levels(data_r$agetype)[levels(data_r$agetype) == "YNG"] <- "Young (18-34)" 
  levels(data_r$agetype)[levels(data_r$agetype) == "MID"] <- "Middle (35-65)" 
  levels(data_r$agetype)[levels(data_r$agetype) == "OLD"] <- "Elder (>65)"
  
  data_r$trainingtype2 <- data_r$trainingtype
  
  levels(data_r$trainingtype2)[levels(data_r$trainingtype2) == "Untrained"] <- "Normal" 
  
  levels(data_r$Gender)[levels(data_r$Gender) == "M"] <- "Male" 
  levels(data_r$Gender)[levels(data_r$Gender) == "F"] <- "Female" 
  levels(data_r$Gender)[levels(data_r$Gender) == "B"] <- "Male" 
  levels(data_r$Gender)[levels(data_r$Gender) == "G"] <- "Female" 
  
  
  levels(data_r$anatomicalLocation)[levels(data_r$anatomicalLocation) == "Thigh"] <- "Upper leg" 
  
  
  levels(data_r$jointAction)[levels(data_r$jointAction) == "knee extensor"] <- "Knee Ext." 
  levels(data_r$jointAction)[levels(data_r$jointAction) == "elbow extensor"] <- "Elbow Ext." 
  levels(data_r$jointAction)[levels(data_r$jointAction) == "ankle plantar flexor"] <- "Plantarflex" 
  levels(data_r$jointAction)[levels(data_r$jointAction) == "elbow flexor"] <- "Elbow Flex." 
  levels(data_r$jointAction)[levels(data_r$jointAction) == "ankle dorsiflexor"] <- "Dorsiflex" 
  levels(data_r$jointAction)[levels(data_r$jointAction) == "hip adductor"] <- "Hip Adduct." 
  
  data_r$mv_method[data_r$mv_method == ""] <- "MV_none"
  data_r$fl_method[data_r$fl_method == ""] <- "fl_none"
  data_r$pa_method[data_r$pa_method == ""] <- "Pa_none"
  data_r$t_method[data_r$t_method == ""] <- "Torq_none"
  data_r$ma_method[data_r$ma_method == ""] <- "MA_none"
  data_r$pcsa_method[data_r$pcsa_method == ""] <- "PCSA_none"
  data_r$f_method[data_r$f_method == ""] <- "Force_none"
  
  
  #remove repeated to get proper paperstats
  data_r_filtered <- data_r %>% distinct(`CovidenceID`, `Muscle`, .keep_all = TRUE)
  
  # colnames(paperstats_r)
  
  output<-list(data_r,data_r_filtered)
  
  return(output)
  
}



result <- loadPaperStats()
# Access the returned variables from the list
paperstats_r <- result[[1]]
# paperstats_r_filtered <-result[[2]]



result2 <- loadPlotdata()
# Access the returned variables from the list
data_r <- result2[[1]]
# data_r_filtered <-result2[[2]]



# now join both data sets
# colnames(data_r)

#<-----------strict studystats vs muscle analysis
# NB muscle rows are distinct. so can only aggregate variables related to distinct muscles. so age range cannot be coinsidered since those rows are removed 

# Join the data frames based on the 'ID' column
# result_df <- paperstats_r_filtered %>%
#   left_join(data_r_filtered, by = c("CovidenceID","Muscle")) %>%
#   select(muscleName, jointType,jointAction,anatomicalLocation)


result_df <- data_r %>%
  select(muscleName, jointType,jointAction,anatomicalLocation)

paperstats_r <- cbind(paperstats_r, result_df)  

# unique(data_r$jointAction)

# unique(paperstats_r$journal)



# data <- read.csv("./included/Plotdata.csv")
# colnames(data)
# 
# 
#  mv_method="Muscle.volume.method",fl_method="Fascicle.length.method",pa_method-"Pennation.angle.method"
#  t_method="Torque.method", ma_method="Moment.arm.method", pcsa_method="PCSA.method", f_method="Force.method"
muscle_order <- c("Biceps Brachii", "Brachialis", "Brachioradialis", "Elbow Flexors",
                  "Triceps Brachii", "Elbow Extensors",
                  "Quadriceps Femoris", "Rectus Femoris","Vastus Intermedius", "Vastus Medialis", "Vastus Lateralis",
                  "Gracilis",
                  "Plantar Flexors","Soleus","Gastrocnemius Lateralis", "Gastrocnemius Medialis","Triceps Surae","Dorsiflexor", "Tibialis Anterior")

custom_colors<-c('black','forestgreen', 'red2', 'orange', 'cornflowerblue', 
                'magenta', 'darkolivegreen4', 'indianred1', 'tan4', 'darkblue', 
                'mediumorchid1','firebrick4',  'yellowgreen', 'lightsalmon', 'tan3',
                "tan1",'darkgray', 'wheat4', '#DDAD4B', 'chartreuse', 
                'seagreen1', 'moccasin', 'mediumvioletred', 'seagreen','cadetblue1',
                "darkolivegreen1" ,"tan2" ,   "tomato3" , "#7CE3D8","gainsboro")

custom_colors <- c(brewer.pal(6, "Set2"),custom_colors)

# brewer.pal(8, "Accent") 
# paletteer_c("grDevices::Dark 3", 8)
# paletteer_c("grDevices::Zissou 1", 8)  
# my_Color_palette <- c("red", "blue", "green", "orange", "purple", "cyan", "magenta", "yellow", "pink", "brown", "black", "gray", "darkgreen", "darkblue", "darkred", "darkorange", "darkcyan", "darkmagenta", "darkyellow")
# 
# custom_colors2  <- c(
#   "dodgerblue2", "#E31A1C", # red
#   "green4",
#   "#6A3D9A", # purple
#   "#FF7F00", # orange
#   "black", "gold1",
#   "skyblue2", "#FB9A99", # lt pink
#   "palegreen2",
#   "#CAB2D6", # lt purple
#   "#FDBF6F", # lt orange
#   "gray70", "khaki2",
#   "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
#   "darkturquoise", "green1", "yellow4", "yellow3",
#   "darkorange4", "brown"
# )




# colnames(paperstats_r)

# data <- read.csv("./included/Plotdata_scored.csv")
# colnames(data)




```

## Plots

```{r Fig3, 4, echo=FALSE}

# journal_data <- paperstats_r %>% distinct(`CovidenceID`, `journal`, .keep_all = TRUE)
muscle_data <- paperstats_r %>% distinct(`CovidenceID`, `aveAge`,`aveHeight`,`aveWeight`,`N`,`Muscle`, .keep_all = TRUE)


#<------------- PieChart
# use 'muscle_data' to get distinct muscle groups per study or use all ST values

pie_data_summary <- paperstats_r %>%
  count(jointAction)

# Calculate percentages
# pie_data_summary <- mutate(pie_data_summary, percentage = n / sum(n) * 100)
# labs <- paste0(round(pie_data_summary$percentage,0), "%")

# Replace multiple labels in jointAction
pie_data_summary <- pie_data_summary %>%
  mutate(jointAction = case_when(
    jointAction == "Dorsiflex" ~ "Dorsiflexion",
    jointAction == "Plantarflex" ~ "Plantarflexion",
    jointAction == "Elbow Ext." ~ "Elbow extension",
    jointAction == "Elbow Flex." ~ "Elbow flexion",
    jointAction == "Hip Adduct." ~ "Hip adduction",
    jointAction == "Knee Ext." ~ "Knee extension",
    # Add more conditions as needed
    TRUE ~ jointAction  # Keep other labels unchanged
  ))

muscle_order1 <- c( "Elbow extension","Elbow flexion", "Hip adduction",
                    "Knee extension" ,"Plantarflexion", "Dorsiflexion")
# Replace multiple labels in jointAction
pie_data_summary <- pie_data_summary %>%
  mutate(jointAction = factor(jointAction, levels = muscle_order1))

pieChartplot <- ggdonutchart(pie_data_summary, "n", label = "n",
   lab.pos = "out", lab.font = "black",
   fill = "jointAction", color = "white",
   palette = custom_colors) +
  labs_pubr()+
  theme(
    axis.title.x = element_blank(),  # Remove x-axis label
    axis.title.y = element_blank(),  # Remove y-axis label
    axis.text  = element_blank(),    # Remove axis text
    axis.text.y =  element_blank(),    # Remove axis ticks
    legend.position = "right"
  )+
  labs(fill = "Muscle function") #title = "Muscle function distribution",

#---new pie-donut plot https://statdoe.com/pie-donut-chart-in-r/
PD = data_r %>%  
  count(agetype)

# PieDonut(PD, aes(agetype, count=n), explodeDonut=TRUE,showRatioThreshold = F,showPieName  = F)
# ,explode = 2 ,r0 = 0.45, r1 = 0.9

pieChartplot_b <- ggdonutchart(PD, "n", label = "n",
   lab.pos = "out", lab.font = "black",
   fill = "agetype", color = "white",
   palette = custom_colors) +
  labs_pubr()+
  theme(
    axis.title.x = element_blank(),  # Remove x-axis label
    axis.title.y = element_blank(),  # Remove y-axis label
    axis.text  = element_blank(),    # Remove axis text
    axis.text.y =  element_blank(),    # Remove axis ticks
    legend.position = "right"
  )+
  labs(fill = "Subject age") #title = "Muscle function distribution


PD2 = muscle_data %>% group_by(muscleName) %>% summarise(n = sum(N))
# sum(PD2$n)

# pieChartplot_c <- ggdonutchart(PD2, "n", label = "n",
#    lab.pos = "out", lab.font = "black",
#    fill = "muscleName", color = "white",
#    palette = custom_colors) +
#   labs_pubr()+
#   theme(
#     axis.title.x = element_blank(),  # Remove x-axis label
#     axis.title.y = element_blank(),  # Remove y-axis label
#     axis.text  = element_blank(),    # Remove axis text
#     axis.text.y =  element_blank(),    # Remove axis ticks
#     legend.position = "right"
#   )+
#   labs(fill = "Muscle (s)") #title = "Muscle function distribution


stacked_bar_chart_N <-  ggplot(PD2, aes(x = reorder(muscleName, -n), y = n)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = custom_colors) +  # Use the defined color palette
  labs( x = "Reported muscle(s)", y = "Number of subjects") + #title = "Number of specific tension values reported by muscle and journal",
  theme_pubr() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + # Rotate x-axis labels
  scale_y_continuous(breaks = seq(0, 500, by = 20)) + # Display whole numbers on the y-axis
   
  # coord_cartesian(ylim = c(0, 10)) +
 theme(
    plot.title = element_text(size = 14, hjust = 0.5),  # Title size and position
    # plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),  # Margins
    # plot.background = element_rect(colour = "black", fill="white", size=1),  # Background color
    plot.background = element_rect(fill="white"),  # Background color
    panel.background = element_rect("white"),  # Panel background color
    panel.grid.major = element_line(color = "lightgray", size = 0.2),  # Gridlines
    axis.title = element_text(size = 14),  # Axis label size
    axis.text = element_text(size = 10)
    )


#----pie chart plot 2
pie_data_summary2 <- paperstats_r %>%
  count(country)
pie_data_summary2$country <- trimws(pie_data_summary2$country)

pieChartplot2 <-ggdonutchart(pie_data_summary2, "n", label = "n",
    lab.font = "black",
   fill = "country", color = "white",
   palette = custom_colors) +
  labs_pubr()+
  theme(
    axis.title.x = element_blank(),  # Remove x-axis label
    axis.title.y = element_blank(),  # Remove y-axis label
    axis.text  = element_blank(),    # Remove axis text
    axis.text.y =  element_blank(),    # Remove axis ticks
    legend.position = "right"
  )+
  labs(fill = "Country")

pie_data_summary3 <- paperstats_r %>%
  count(journal)
pie_data_summary3$journal <- trimws(pie_data_summary3$journal)

pieChartplot3 <-ggdonutchart(pie_data_summary3, "n", label = "n",
    lab.font = "black",
   fill = "journal", color = "white",
   palette = custom_colors) +
  labs_pubr()+
  theme(
    axis.title.x = element_blank(),  # Remove x-axis label
    axis.title.y = element_blank(),  # Remove y-axis label
    axis.text  = element_blank(),    # Remove axis text
    axis.text.y =  element_blank(),    # Remove axis ticks
    legend.position = "right"
    # legend.text=element_text(size=9),
    
  )+
  labs(fill = "Journal")+
  guides(fill = guide_legend(ncol = 1)) 
  # labs(title = "Body part distribution", fill = "Anatomical location")


data_summary_b <- paperstats_r %>%
  count(muscleName)

stacked_bar_chart <-  ggplot(data_summary_b, aes(x = reorder(muscleName, -n), y = n)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = custom_colors) +  # Use the defined color palette
  labs( x = "Reported muscle(s)", y = "Number of reported ST Values") + #title = "Number of specific tension values reported by muscle and journal",
  theme_pubr() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + # Rotate x-axis labels
  scale_y_continuous(breaks = seq(0, 30, by = 2)) + # Display whole numbers on the y-axis
   
  # coord_cartesian(ylim = c(0, 10)) +
 theme(
    plot.title = element_text(size = 14, hjust = 0.5),  # Title size and position
    # plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),  # Margins
    # plot.background = element_rect(colour = "black", fill="white", size=1),  # Background color
    plot.background = element_rect(fill="white"),  # Background color
    panel.background = element_rect("white"),  # Panel background color
    panel.grid.major = element_line(color = "lightgray", size = 0.2),  # Gridlines
    axis.title = element_text(size = 14),  # Axis label size
    axis.text = element_text(size = 10)
    )



data_summary_c <- paperstats_r %>%
  count(year)
# Create the stacked bar chart
stacked_bar_chart_c <- ggplot(data_summary_c, aes(x = factor(year), y = n)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = custom_colors) +
  labs(x = "Year", y = "Number of reported ST Values") +
  theme_pubr() +  # Change to a minimal theme for a cleaner look
  scale_y_continuous(breaks = seq(0, 15, by = 2)) + # Display whole numbers on the y-axis

  # Keep only x-axis ticks that have a y-value
  scale_x_discrete(drop = TRUE) +
  
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    # plot.title = element_text(size = 14, hjust = 0.5),
    plot.background = element_rect(fill = "white"),
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(color = "lightgray", size = 0.2),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12)
  )


 #<---- Compile plots
#paper stats plot1
piechartplots <- plot_grid(pieChartplot3,pieChartplot2,nrow = 1,labels = c("B","C"), rel_widths = c(1, 1), rel_heights = c(1,1))
fig1 <- plot_grid(stacked_bar_chart_c,piechartplots,
nrow = 2, rel_heights = c( 1,0.9),labels = c("A"))+ theme(panel.background = element_rect(color = "white",fill = "white")) 


saveFig(fig1,"Fig3 paperstats",12,9)

# saveFig(topplot2,"paperstats_author_journal",12,8)


piechartplots2 <- plot_grid(pieChartplot,pieChartplot_b,nrow = 1,labels = c("C","D"), rel_widths = c(1, 1), rel_heights = c(1,1))
fig1b <- plot_grid(stacked_bar_chart,stacked_bar_chart_N,piechartplots2,
nrow = 3, rel_heights = c( 1,1,0.5),rel_widths = c(1,1,1),labels = c("A","B"))+ theme(panel.background = element_rect(color = "white",fill = "white")) 
fig1b



saveFig(fig1b,"Fig4 STstats",11,12)
```

### Ave ST values
```{r Fig6 , echo=FALSE}
custom_colors2 <- c(brewer.pal(8, "Dark2"),custom_colors)

muscle_order2 <- c("BIC", "BRA", "BRD", "EF",
                  "TRI", "EE",
                  "QF", "RF","VI", "VM", "VL",
                  "GRA",
                  "PF","SOL","GL", "GM","TS","DF", "TA")

paperstats_r <- paperstats_r %>%
  mutate(Muscle = factor(Muscle, levels = muscle_order2)) %>% 
  mutate(anatomicalLocation = factor(anatomicalLocation, levels = c("Upper arm","Upper leg", "Lower leg")))

topplot <- ggplot(paperstats_r, aes(x = aveST, y = reorder(studyID, year))) +
  geom_point(aes(color = Muscle, shape = anatomicalLocation)) +
  labs(
    y = "Author",
    x = expression("Specific tension "~(N/cm^2))
  ) +
  theme_pubr(legend = 'none') +  # Remove legends
  theme(
    plot.title = element_text(size = 14, hjust = 0.5),
    plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
    plot.background = element_rect(fill = "white"),
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(color = "lightgray", size = 0.2),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 10)
  )+
  scale_color_manual(values = custom_colors2)

 
data_r <- data_r %>%
  mutate(Muscle = factor(Muscle, levels = muscle_order2))



 fig8complete <- ggplot(data_r, aes(y = aveST)) +
  geom_boxplot(outlier.shape = NA, width = 0.08) +  # Turn off the outliers outlier.shape = NA
  geom_jitter(aes(x = 0, color=Muscle, shape=anatomicalLocation), width = 0.009, alpha = 1) +  # Show all data points with jitter
   # stat_summary(aes(x = 0),fun = median, geom = "point", shape = 18, size = 0, color = "red", position = position_dodge(0.75))+
     annotate("text", x = 0, y = median(data_r$aveST), label = round(median(data_r$aveST),1), vjust = -0.5, hjust = -0.4, size = 4) +

   # geom_text(aes(x = 0, y = median(aveST), label = median(aveST), color = "red"), hjust = -1, size = 4) +
  theme_pubr(legend='right') + labs(y = expression("Specific tension "~(N/cm^2)),color="Muscle",
    shape="Anatomical location") +
   theme(axis.title.x = element_blank(),axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),axis.title = element_text(size = 14),  # Axis label size
    axis.text = element_text(size = 10),) +
  scale_color_manual(values = custom_colors2)

fig_five <- plot_grid(topplot,fig8complete,ncol = 2, rel_widths = c(1, 0.7),labels = c("A","B"))
fig_five
saveFig(fig_five,'Fig6 ST_overall',9,7)



```
# grouped figure for abstract
```{r abstract_Fig}

abstract_fig_data <- data_r %>% select(CovidenceID,studyID,Muscle,muscleName,newScore,aveST,anatomicalLocation)



# Convert muscleName to a factor with levels in the predefined order
abstract_fig_data$muscleName <- factor(abstract_fig_data$muscleName, levels = muscle_order)


summary_stats <- abstract_fig_data %>%
  group_by(anatomicalLocation, muscleName, newScore) %>%
  summarise(
    mean_aveST = mean(aveST, na.rm = TRUE),
    sd_aveST = sd(aveST, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  arrange(desc(newScore))

library(write_xlsx)
writexl::write_xlsx(summary_stats,"./grouped_data2.xlsx")

# ggplot(summary_stats, aes(x = mean_ST, y = reorder(muscleName, newScore), size = newScore, fill = anatomicalLocation)) +
#         geom_point(shape = 21)

# Dodging function
# reorder(anatomicalLocation, newScore)



ggplot(summary_stats, aes(x=reorder(anatomicalLocation, newScore), y=mean_ST, ymin=lower, ymax=upper,fill=factor(newScore))) + 
#specify position here
  geom_linerange(size=5,position=position_dodge(width = 0.5)) +
#specify position here too
  geom_point(size=3, shape=21, colour="white", stroke = 0.5,position=position_dodge(width = 0.5)) +
  coord_flip() +
  theme_minimal()


plot_anatomical_loc_grp <- function(abstract_fig_data) {
  # Calculate mean and standard deviation for each muscleName and newScore group
summary_stats <- abstract_fig_data %>%
  group_by(anatomicalLocation,newScore) %>%
  summarise(
    mean_ST = mean(aveST, na.rm = TRUE),
    sd_ST = sd(aveST, na.rm = TRUE)
    # anatomicalLocation = unique(anatomicalLocation)
  ) %>%
  ungroup()%>%
  # mutate(
  #   lower = mean_ST - sd_ST,
  #   upper = mean_ST + sd_ST
  # ) %>%
  arrange(desc(newScore)) 

fig <- ggplot(summary_stats, aes(y = mean_ST, x =anatomicalLocation,group=newScore, fill = newScore)) +
  geom_errorbar(aes(ymin = mean_ST-sd_ST, ymax = mean_ST+sd_ST),data = summary_stats, width = 0.2, position=position_dodge(0.65)) +
  geom_point(shape = 21,size=5, position=position_dodge(0.65)) + 
 scale_fill_continuous(low = "grey80", high = "black") +
  # coord_flip()+
  theme_pubr(legend='right')+
  
  labs(
    # title = "Mean aveST with Standard Deviation by Muscle Group and Score",
    x = "Anatomical Location",
    y = expression("Specific tension "~(N/cm^2)),
    size = "Score",
    fill = "Score"
  )
return (fig)
}


############ group by muscle name

plot_muscle_group <- function(abstract_fig_data) {
  # Calculate mean and standard deviation for each muscleName and newScore group
summary_stats <- abstract_fig_data %>%
  group_by(anatomicalLocation, muscleName, newScore) %>%
  summarise(
    mean_aveST = mean(aveST, na.rm = TRUE),
    sd_aveST = sd(aveST, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  arrange(desc(newScore))

# Create the staggered plot with subgroups for each anatomical location
fig <- ggplot(summary_stats, aes(y = mean_aveST, x = reorder(muscleName, newScore),group=newScore, fill = newScore)) +
  geom_errorbar(aes(ymin = mean_aveST - sd_aveST, ymax = mean_aveST + sd_aveST), width = 0.2, color = "black", position = position_dodge(0.65)) +
  geom_point(shape = 21, size = 5, color = "black", stroke = 0.5, position = position_dodge(0.65)) +
  scale_fill_continuous(low = "grey80", high = "black") +
  coord_flip() +
  theme_pubr(legend = 'right') +
  labs(
    # title = "Mean aveST with Standard Deviation by Muscle Group and Score",
    x = "Muscle(s)",
    y = expression("Specific tension " ~ (N/cm^2)),
    size = "Score",
    fill = "Score"
  ) +
  theme(axis.text.y = element_text(angle = 0, hjust = 1))

return (fig)
}

#plot and save results
# new_plot1 <- plot_anatomical_loc_grp(abstract_fig_data)
# 
# new_plot2 <- plot_muscle_group(abstract_fig_data)
# 
# saveFig(new_plot1,'abstract figure- groupby anatomical location and score',8,6)
# saveFig(new_plot2,'group by muscle and score',8,6)
# 


############# redo to make look same but changed

abstract_fig_data2 <-abstract_fig_data %>%
  group_by(studyID,muscleName,newScore) %>%
  summarise(
    mean_ST = mean(aveST, na.rm = TRUE),
    sd_ST = sd(aveST, na.rm = TRUE),
    # anatomicalLocation = unique(anatomicalLocation),
    studyID = unique(studyID)
    
  ) %>%
  ungroup()%>%
  arrange(desc(newScore)) %>% 
  # mutate(studyID = reorder(studyID, newScore))
  mutate(studyID = factor(studyID, levels = unique(studyID[order(newScore)])))








# minor_breaks <- seq(0, 75, by = 5)

# + scale_x_continuous(breaks = minor_breaks, minor_breaks = minor_breaks)


# new_plot3 <-
 ggplot(abstract_fig_data2, aes(x = mean_ST, y = studyID,fill = muscleName)) + # fill = newScore
  geom_errorbarh(aes(xmin = mean_ST - sd_ST, xmax = mean_ST + sd_ST), color = "black") +
  geom_point(shape = 21, size = newScore) +
  # scale_fill_continuous(low = "grey80", high = "black") +
   # scale_fill_continuous(low = "#E6E6FA", high = "#800099")+
  facet_grid(muscleName ~ ., scales = "free", space = "free") +
  theme_pubr() +
  theme(strip.text.y = element_text(angle = 0),
        panel.grid.major = element_line(color = "gray", size = 0.2),
        panel.grid.minor = element_line(color = "gray", size = 0.1)) +
  labs(
    y = "Author",
    x = expression("Specific tension "~(N/cm^2)),
    fill = "Score"  # Changed from 'color' to 'fill' to match the fill aesthetic
  )
  


saveFig(new_plot3,'abstract figure',9,9)





# ggplot(abstract_fig_data, aes(x = aveST, y = reorder(studyID, newScore))) +
#   geom_point(aes(color = Muscle, shape = '0',size=newScore)) + #shape = anatomicalLocation
#   facet_grid(muscleName  ~ ., scales = "free", space = "free") +
#   labs(
#     y = "Author",
#     x = expression("Specific tension "~(N/cm^2))
#   ) +
#   theme_pubr(legend = 'none') +  # Remove legends
#   theme(strip.text.y = element_text(angle = 0),
#     plot.title = element_text(size = 14, hjust = 0.5),
#     plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
#     plot.background = element_rect(fill = "white"),
#     panel.background = element_rect(fill = "white"),
#     panel.grid.major = element_line(color = "lightgray", size = 0.2),
#     axis.title = element_text(size = 14),
#     axis.text = element_text(size = 10)
#   )+
#   scale_color_manual(values = custom_colors2)




# option1 <- ggplot(abstract_fig_data2, aes(x = mean_ST, y = studyID)) +
#   geom_errorbarh(aes(xmin = mean_ST - sd_ST, xmax = mean_ST + sd_ST), color = "black")+
#   geom_point(aes(color = muscleName, shape = '0',size=newScore)) + #shape = anatomicalLocation
#   
#   facet_grid(muscleName  ~ ., scales = "free", space = "free") +
#   labs(
#     y = "Author",
#     x = expression("Specific tension "~(N/cm^2)),
#     size = "Score",
#   ) +
#   theme_pubr(legend = 'none') +  # Remove legends
#   theme(strip.text.y = element_text(angle = 0),
#     plot.title = element_text(size = 14, hjust = 0.5),
#     plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
#     plot.background = element_rect(fill = "white"),
#     panel.background = element_rect(fill = "white"),
#     panel.grid.major = element_line(color = "lightgray", size = 0.2),
#     axis.title = element_text(size = 14),
#     axis.text = element_text(size = 10)
#   )
# 
# option1

revisied_color <- ggplot(abstract_fig_data2, aes(x = mean_ST, y = studyID)) + 
  geom_errorbarh(aes(xmin = mean_ST - sd_ST, xmax = mean_ST + sd_ST), color = "black") +
  geom_point(aes(shape = '0', size = newScore, color = muscleName)) +  # Adjust size if needed; use a fixed value or map to a variable
  scale_color_discrete(guide = "none") + 
  # scale_shape_manual(guide = "none") +
  facet_grid(muscleName ~ ., scales = "free", space = "free")+
  theme_pubr() +
  theme(strip.text.y = element_text(angle = 0),
        panel.grid.major = element_line(color = "gray", size = 0.2),
        panel.grid.minor = element_line(color = "gray", size = 0.1)) +
    labs(
    y = "Author",
    x = expression("Specific tension "~(N/cm^2)),
    # shape='',
    size='Score'
    # fill = "Score"  # Use 'fill' for the fill aesthetic
    # color = "Muscle Name"  # Use 'color' for the color aesthetic
  ) +
  guides(
    color = "none",  # Turn off the legend for color
    shape = "none",  # Turn off the legend for shape
)

saveFig(revisied_color,'abstract figure colored',9,11)

####add color

library(patchwork)

# List of unique muscle names
muscle_names <- unique(abstract_fig_data2$muscleName)

# Create individual plots
plot_list <- lapply(muscle_names, function(muscle) {
  data_subset <- subset(abstract_fig_data2, muscleName == muscle)
  
  ggplot(data_subset, aes(x = mean_ST, y = studyID, fill = newScore)) +
    geom_errorbarh(aes(xmin = mean_ST - sd_ST, xmax = mean_ST + sd_ST), color = "black") +
    geom_point(shape = 21, size = 3) +
    # scale_fill_gradientn(colors = c("#E6E6FA", "#800080")) +  # Adjust color gradient
    theme_pubr() +
    theme(strip.text.y = element_text(angle = 0),
          panel.grid.major = element_line(color = "gray", size = 0.2),
          panel.grid.minor = element_line(color = "gray", size = 0.1)) +
    labs(
      y = "Author",
      x = expression("Specific tension "~(N/cm^2)),
      fill = "Score"
    ) +
    ggtitle(muscle)  # Add facet label as title for clarity
})

# Combine plots into a single plot
combined_plot <- wrap_plots(plot_list, ncol = 1)  # Adjust `ncol` as needed

combined_plot


plot_list
```



### plot muscle function, location etc vs ST

```{r Fig5}
plot_box_no_grps <- function(xcol,xlabel){
   my_comparisons <- list( c("Male", "Female") )
   
   
  grp2 <- ggboxplot(data_r, x = xcol, y = "aveST",
                palette ="jco",add = "jitter",
                xlab = xlabel)+ stat_compare_means(comparisons = xcol)
 
 
 grp2 <- grp2+theme_pubr() + labs(y = expression("Specific tension "~(N/cm^2)))+theme(axis.text = element_text(size = 12))   
 

 
   # stat_compare_means(comparisons = my_comparisons)+ # Add pairwise comparisons p-value
  # stat_compare_means(label.y = 50)

 return (grp2)
  
}




data_r <- data_r %>%
  mutate(anatomicalLocation = factor(anatomicalLocation, levels = c("Upper arm","Upper leg", "Lower leg")))

data_r <- data_r %>%
  mutate(jointAction = factor(jointAction, levels = c("Elbow Flex.","Elbow Ext.", "Hip Adduct.", "Knee Ext.", "Plantarflex", "Dorsiflex")))

box1c <- plot_box_no_grps("anatomicalLocation","Anatomical location")+
  theme(legend.position = "none") 

box2c <- plot_box_no_grps("jointAction","Function")
box3c <- plot_box_no_grps("trainingtype","Training status")+
  theme(legend.position = "none") 
box4c <- plot_box_no_grps("jointType","Mono/Biarticular")+
  theme(legend.position = "none") 
box5c <- plot_box_no_grps("FastSlow","Fiber type (Fast/Slow)")+
  theme(legend.position = "none") 


box1c <-ggboxplot(data_r, x = "anatomicalLocation", y = "aveST",
          palette = "jco", add = "jitter",
          xlab = "Anatomical location") +
  stat_compare_means(comparisons = list( c("Upper arm", "Lower leg"), c("Upper leg", "Lower leg")), hide.ns = TRUE,map_signif_level = TRUE,annotations="***")+theme_pubr() + labs(y = expression("Specific tension "~(N/cm^2)))+theme(axis.text = element_text(size = 12)) 

# , c("Normal", "Trained") c("Normal", "Untrained"),
box3c <-ggboxplot(data_r, x = "trainingtype", y = "aveST",
          palette = "jco", add = "jitter",
          xlab = "Training status") +
  stat_compare_means(comparisons = list( c("Trained", "Untrained")), hide.ns = TRUE,map_signif_level = TRUE,annotations="***")+theme_pubr() + labs(y = expression("Specific tension "~(N/cm^2)))+theme(axis.text = element_text(size = 12)) 



# box5c <-ggboxplot(data_r, x = "FastSlow", y = "aveST",
#           palette = "jco", add = "jitter",
#           xlab = "Training status") +
#   stat_compare_means(comparisons =list(c("60/40", "Slow")), hide.ns = TRUE,map_signif_level = TRUE,annotations="***")+theme_pubr() + labs(y = expression("Specific tension "~(N/cm^2)))+theme(axis.text = element_text(size = 12)) 


#removed Bi articular etc
# fig7complete <- compile_plot(box2c,box1c,box3c,box4c,box5c)
# saveFig(fig7complete,'breakdown4',15,8)



#--Add table
# Provided JSON-like data
json_data <- fromJSON(txt  = "tableConvert.com_gh9ywa.json") 
# Rename the column
colnames(json_data)[1] <- "Abbreviation"
# colnames(json_data)[3] <- "Fiber composition (fast % / slow %)"

# Replace multiple labels in jointAction
json_data <- json_data %>%
  mutate(`Muscle function` = case_when(
    `Muscle function` == "ankle dorsiflexor" ~ "Ankle dorsiflexion",
    `Muscle function` == "ankle plantar flexor" ~ "Ankle plantarflexion",
    `Muscle function` == "elbow extensor" ~ "Elbow extension",
    `Muscle function` == "elbow flexor" ~ "Elbow flexion",
    `Muscle function` == "hip adductor" ~ "Hip adduction",
    `Muscle function` == "knee extensor" ~ "Knee extension",
    # Add more conditions as needed
    TRUE ~ `Muscle function`  # Keep other labels unchanged
  ))

#Sort
custom_order <- c( "Upper arm","Upper Leg","Lower leg")
# Sort the data frame based on custom orders
json_data <- json_data %>%
  arrange(factor(`Anatomical location`, levels = custom_order),factor(`Muscle Name`, levels = muscle_order))


breakdown4_t <- plot_grid(box2c,box5c,rel_widths = c(1,0.6),rel_heights = c(1,1),labels = c("A","B"))
breakdown4_b <- plot_grid(box1c,box3c,rel_widths = c(1,1),rel_heights = c(1,1),labels = c("C","D"))

breakdown4_b2 <- plot_grid(breakdown4_t,breakdown4_b, ncol = 1,align = 'v',axis = 'lr')

#ttheme("blank")

# old figure
# tbl <- ggtexttable(json_data, rows = NULL, theme = ttheme("blank")) %>%
#   tab_add_hline(at.row = 1:2, row.side = "top", linewidth = 2) %>%
#   tab_add_hline(at.row = 20, row.side = "bottom", linewidth = 3, linetype = 1)
# 
# 
# fig7complete <- plot_grid(tbl+ theme(panel.background = element_rect(color = "white",fill = "white")),breakdown4_b2, nrow = 2,rel_heights = c(0.8,1))
# 
# # fig7complete <-ggarrange(tbl, breakdown4_b2,
# #           ncol = 1, nrow = 2)
# 
# fig7complete
# 
# saveFig(fig7complete,'breakdown4',12,14)

# <----------------------------------------------New plot
Fiber_data <- data_r %>% select(c('muscleName','aveST','Type1','Type2A','Type2X'))
melted_df <- pivot_longer(Fiber_data, cols = starts_with('Type'), names_to = 'fiber_type', values_to = 'percentage')


# Assuming df is your dataframe and the column is named 'type_column'
melted_df$fiber_type <- gsub("Type1", "Type 1", melted_df$fiber_type)
melted_df$fiber_type <- gsub("Type2A", "Type 2A", melted_df$fiber_type)
melted_df$fiber_type <- gsub("Type2X", "Type 2X", melted_df$fiber_type)

# p <- ggplot(melted_df, aes(percentage, aveST, color = fiber_type)) +
#   geom_point() +
#   stat_smooth(aes(fill = fiber_type, color = fiber_type), method = "lm", formula = y ~ x) +
#   stat_regline_equation(
#     aes(label =  paste(..eq.label.., ..adj.rr.label.., sep = "~~~~")),
#     formula = formula
#   ) +
#   theme_bw()
# ggpar(p, palette = "jco")

 # my_Color_palette <- paletteer_c("grDevices::Zissou 1", 18)


#separate figure to show new panel
# Fiber_ST <- ggscatter(
#   melted_df, x = "percentage", y = "aveST",
#   color = "muscleName", palette = custom_colors
#   # add = "reg.line", 
#   # line.color = "red" 
#   ) + geom_smooth(method = "lm", se = FALSE, color = "black")+
#   facet_wrap(~fiber_type) +
#   stat_cor(label.y = 80) +
#   stat_regline_equation(label.y = 77)+
#   labs(x = "Fiber composition (%)", y = expression("Specific tension "~(N/cm^2)),
#        color = "Muscle", title = "Specific Tension vs. Fiber Composition ")
# # Fiber_ST
# 
# saveFig(Fiber_ST,'ST_FiberComp',10,7)


# box5c <- ggscatter(
#   melted_df, x = "percentage", y = "aveST")+ 
#   geom_smooth(method = "lm", color = "red", size = 1.5, se = FALSE) +
#   facet_wrap(~fiber_type) +
#   stat_cor(aes(label = ..r.label..),
#            label.y = 80) +
#   stat_regline_equation(label.y = 75)+
#   labs(x = "Fiber composition (%)", y = expression("Specific tension "~(N/cm^2)),
#        color = "Muscle")

# ggscatter(
#   melted_df, x = "percentage", y = "aveST")+
#   geom_smooth(method = "lm", color = "red", size = 1.5, se = FALSE) +
#   facet_wrap(~fiber_type) +
#   stat_cor(aes(label = ..r.label..),
#            label.y = 80) +
#   stat_regline_equation(label.y = 75)+
#   labs(x = "Fiber composition (%)", y = expression("Specific tension "~(N/cm^2)),
#        color = "Muscle")+
# stat_cor(method = "spearman", label.x = -5, label.y = 30)  # pearson spearman kendall

# library(ggpmisc)
#  # Plotting with linear regression lines and p-values
# ggplot(melted_df, aes(x = percentage, y = aveST)) +
#   geom_point() +  # Scatter plot
#   geom_smooth(method = "lm", aes(color = "Linear fit"), size = 1.5, se = FALSE) +  # Linear regression line
#   stat_poly_eq(
#     aes(label = paste(..eq.label.., sep = "~~~", "p = ", format.pval(..p.value.., digits = 2))),
#     formula = y ~ x, parse = TRUE,
#     size = 3, label.x = "right", label.y = "top",
#     color = "red", fill = "white"
#   ) +
#   facet_wrap(~ fiber_type, scales = "free") +  # Facet by fiber_type
#   labs(
#     x = "Fiber composition (%)",
#     y = expression("Specific tension "~(N/cm^2)),
#     color = "Fit"
#   ) +
#   theme_minimal()



# Plotting with customized linear regression per facet 
box5c <-ggplot(melted_df, aes(x = percentage, y = aveST)) + 
  geom_point() +  # Scatter plot
  labs(x = "Fiber composition (%)", y = expression("Specific tension "~(N/cm^2)),
       color = "Muscle") +
  facet_wrap(~ fiber_type, nrow = 1, ncol = 3, scales = "free") +  # Facet by fiber_type in 1 row and 3 columns
  # geom_smooth(
  #   data = subset(melted_df, fiber_type == unique(melted_df$fiber_type)[2]),  # Filter for the second fiber_type
  #   method = "lm", color = "red", size = 1.5, se = FALSE  # Customize linear regression appearance
  # ) +
  theme_pubr()+
  
  theme(strip.background = element_blank(),  # Remove facet strip background for cleaner appearance
        strip.text = element_text(size = 12, face = "bold"))  # Adjust facet strip text appearance



# colnames(json_data)

json_data <- json_data %>%
  rename("Type 1" = "%MHC-1",
         "Type 2A" = "%MHC-2A",
         "Type 2X" = "%MHC-2X")





####<-------------export table to word
library(flextable)
library(officer)

json_data_table <- json_data %>%
  flextable() %>% 
  theme_vanilla() %>% 
  align(align = "center", part = "all") %>% 
  autofit() %>% 
  width(j = 1, width = 1.2) %>%   
  add_header_row(values = c("","*Fiber composition (%)",""),
                 colwidths = c(2, 3, 2)) %>%
  hline(i = 1, border = fp_border_default(width = 0), part = "header") %>%
  hline(i = 1, j = 3:5, border = fp_border_default(width = 1), part = "header")

json_data_table

# Create a new Word document
doc <- read_docx()
# Add flextable to the Word document
doc <- body_add_flextable(doc, value = json_data_table)
# Save the Word document
print(doc, target = "output_document.docx")




# tbl <- json_data %>%
#   flextable() %>% 
#   theme_vanilla() %>% 
#   align(align = "center", part = "all") %>% 
#   autofit() %>% width(j = 1, width = 1.2)%>%   
#   add_header_row(values = c("","*Fiber composition (%)",""),
#   colwidths = c(2,3,2)) %>%
#   hline(i =1,border = fp_border_default(width = 0), 
#             part = "header")%>%
#   hline(i =1,j=3:5,border = fp_border_default(width = 1), 
#             part = "header") %>% as_raster()
# 
# 
# # library(ftExtra)
# 
# gg2 <- ggplot() + 
#   theme_void() + 
#   annotation_custom(rasterGrob(tbl), xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf)
# 
# # gg2


breakdown4_t <- plot_grid(box2c,box1c,rel_widths = c(1,0.6),rel_heights = c(1,1),labels = c("A","B"))
breakdown4_b <- plot_grid(box5c,box3c,rel_widths = c(1,0.6),rel_heights = c(1,1),labels = c("C","D"))

breakdown4_b2 <- plot_grid(breakdown4_t,breakdown4_b, ncol = 1,align = 'v',axis = 'lr')

# breakdown4_b2
# saveFig(breakdown4_b2,'breakdown4b',12,10)


# fig7complete <- plot_grid(tbl+ theme(panel.background = element_rect(color = "white",fill = "white")),breakdown4_b2, nrow = 2,rel_heights = c(0.8,1))

# p111 <- ggdraw() + draw_image("Fig5_table.png", scale = 1)

# fig7complete <- plot_grid(gg2+ theme(panel.background = element_rect(color = "white",fill = "white")),breakdown4_b2, nrow = 2, ncol = 1,rel_heights = c(0.7,1))

fig7complete <- breakdown4_b2

# fig7complete
saveFig(fig7complete,'Fig5 ST_musclegrps',10,8)




```
### Weightedd values
```{r}
Study_order <- paperstats_r %>%
  arrange(desc(year)) %>%  # Arrange rows based on the 'year' variable
  select(studyID, year)




# max(data_r$newScore)


# Assuming df is your dataframe with 'Score' and 'ST' columns
df=data_r

df <- df %>%
  mutate(studyID = factor(studyID, levels = rev(unique(Study_order$studyID))))

# Normalize 'Score'
# df$Normalized_Score <- (df$newScore - min(df$newScore)) / (max(df$newScore) - min(df$newScore))

df$Normalized_Score <- (df$newScore ) /31 # max(df$newScore)

# df$Normalized_Score <- (df$newScore - min(df$newScore)) / (31 - min(df$newScore))

df$Normalized_Cumulative <- cumsum(df$Normalized_Score)

# Multiply 'Normalized_Score' by 'ST'
df$Adjusted_Score <- df$Normalized_Score * df$aveST

mean(df$Adjusted_Score, na.rm = TRUE)
# Calculate 95% CI
t.test(df$Adjusted_Score, na.rm = TRUE)$conf.int

cal_CI <- function(ST) {
  sample.mean <- mean(ST)
print(sample.mean)

sample.n <- length(ST)
sample.sd <- sd(ST)
sample.se <- sample.sd/sqrt(sample.n)
print(sample.se)

alpha = 0.05
degrees.freedom = sample.n - 1
t.score = qt(p=alpha/2, df=degrees.freedom,lower.tail=F)
print(t.score)

margin.error <- t.score * sample.se
print(margin.error)
lower.bound <- sample.mean - margin.error
upper.bound <- sample.mean + margin.error
print(c(lower.bound,upper.bound))
  
}

cal_CI(df$Adjusted_Score)

cal_CI(df$aveST)

median(df$Adjusted_Score, na.rm = TRUE)
range(df$aveST)
range(df$Adjusted_Score)

Q1 <- quantile(df$aveST, 0.25)
Q3 <- quantile(df$aveST, 0.75)
IQR_value <- Q3 - Q1
# Print the IQR
print(IQR_value)

library(matrixStats)
# Weighted_mean <- 
  matrixStats::weightedMedian(df$aveST, df$Normalized_Cumulative)  

# median <- 
  median(df$aveST)  
  
  mean(df$aveST) 
  sd(df$aveST) 

  Q1
  Q3
  
  
IQR_weighted_median <- function(df) {
  
# Sort data by aveST (if not already sorted)
df <- df[order(df$aveST), ]

# Calculate cumulative weights
df$cum_weights <- cumsum(df$Normalized_Cumulative)

# Find the total weight
total_weight <- sum(df$Normalized_Cumulative)

# Calculate weighted quartiles
weighted_Q1 <- approx(df$cum_weights, df$aveST, xout = total_weight / 4)$y
weighted_Q3 <- approx(df$cum_weights, df$aveST, xout = 3 * total_weight / 4)$y

# Calculate weighted IQR
weighted_IQR <- weighted_Q3 - weighted_Q1

# Print the results
cat("Weighted Q1:", weighted_Q1, "\n")
cat("Weighted Q3:", weighted_Q3, "\n")
cat("Weighted IQR:", weighted_IQR, "\n")
  
}  

IQR_weighted_median(df)


# library(spatstat)
# weighted.median(df$aveST, df$Normalized_Score)




df$studyID_adjusted <- paste(data_r$studyID,'(',data_r$Muscle,',',round(df$Adjusted_Score,1), 'N/cm² )')




 fig9ccomplete <- ggplot(df, aes(x = newScore, y = aveST)) +
  geom_point(color = "black", shape = 16, alpha = 0.5) +  # Scatter plot for all points
  geom_smooth(method = "lm", se = FALSE, color = "red") +  # Single linear regression line
  stat_regline_equation(label.x = 20, label.y = 5, aes(label = paste(..eq.label.., ..adj.rr.label.., sep = "~~~~"))) +
  theme_bw() +
  labs(y = expression("Specific tension "~(N/cm^2)), x = 'Score') +
  theme(
    axis.title = element_text(size = 14),  
    axis.text = element_text(size = 10),
    plot.title = element_text(size = 14, hjust = 0.5),
    panel.background = element_rect(color = "white", fill = "white")
  )
 
 fig9ccomplete
 saveFig(fig9ccomplete,'Fig7 ST_score',8,6)
 
 #Create plot to show before and after 
 df$studyID_adjusted1 <- paste(data_r$studyID,'(',data_r$Muscle,')')
 
 df <- df %>% 
  group_by(studyID_adjusted1) %>% 
  mutate(group_number = row_number())
 
 
 
 df$studyID_adjusted2 <- paste(df$studyID,'(',df$Muscle, df$group_number,')')
 
df$year <- str_extract(df$studyID,"\\d{4}")
df$year <- factor(df$year)
df$studyID_adjusted2 <- factor(df$studyID_adjusted2)
df$studyID_adjusted2 <- factor(df$studyID_adjusted2, levels = unique(df$studyID_adjusted2[order(df$year)]))

 # ggplot(df) +
 #  geom_segment(aes(x = aveST, xend = Adjusted_Score, y = studyID_adjusted2, yend = studyID_adjusted2), color = "grey") +
 #  geom_point(aes(x = aveST, y = studyID_adjusted2), color = rgb(0.2, 0.7, 0.1, 0.5), size = 3) +
 #  geom_point(aes(x = Adjusted_Score, y = studyID_adjusted2), color = rgb(0.7, 0.2, 0.1, 0.5), size = 3) +
 #  geom_vline(xintercept = mean(df$aveST), linetype = "dashed", color = "green") +  # Vertical line for green average
 #  geom_vline(xintercept = mean(df$Adjusted_Score), linetype = "dashed", color = "red") +  # Vertical line for red average
 #  theme_pubr() +
 #  theme(legend.position = "right") +
 #  xlab("") +
 #  ylab(expression("Specific tension "~(N/cm^2)))
 
  # df$studyID_adjusted3 <- paste(df$Muscle, df$group_number)
 
 
 ST_change <- ggplot(df) +
  geom_segment(aes(x = aveST, xend = Adjusted_Score, y = studyID_adjusted2, yend = studyID_adjusted2), color = "grey") +
  geom_point(aes(x = aveST, y = studyID_adjusted2, color = "Unweighted"), size = 3) +
  geom_point(aes(x = Adjusted_Score, y = studyID_adjusted2, color = "Weighted"), size = 3) +
 scale_color_manual(values = c("Unweighted" = "black", "Weighted" = "darkgrey"), 
                    labels = c(
                      # bquote(Unweighted ~ ST ~ "," ~ average ~ "=" ~ .(round(mean(df$aveST))) ~ N/cm^2),
                      # bquote(Weighted ~ ST ~ "," ~ average ~ "=" ~ .(round(mean(df$Adjusted_Score))) ~ N/cm^2))
                      bquote(Unweighted ~ ST),
                      bquote(Weighted ~ ST ~ "," ~ median ~ "= 26.8" ~ N/cm^2))
                    ) +
  # geom_vline(xintercept = mean(df$aveST), linetype = "dashed", color = "black") +  # Vertical line for green average
  geom_vline(xintercept =26.8 , linetype = "dashed", color = "darkgrey") + #mean(df$Adjusted_Score)
  theme_pubr() +
labs(
    y = "Author",
    x = expression("Specific tension "~(N/cm^2)),
    color = " "
  )+
  theme(legend.position = "bottom")
 saveFig(ST_change,'Fig8 unweighted_weighted',8,15)

 ST_change
 
 # ST_change2 <- ggplot(df) +
 #  geom_segment(aes(x = aveST, xend = Adjusted_Score, y = studyID, yend = studyID), color = "grey") +
 #  geom_point(aes(x = aveST, y = studyID, color = "Unweighted"), size = 3) +
 #  geom_point(aes(x = Adjusted_Score, y = studyID, color = "Weighted"), size = 3) +
 # scale_color_manual(values = c("Unweighted" = "black", "Weighted" = "darkgrey"), 
 #                    labels = c(bquote(Unweighted ~ ST ~ "," ~ average ~ "=" ~ .(round(mean(df$aveST))) ~ N/cm^2),
 #                               bquote(Weighted ~ ST ~ "," ~ average ~ "=" ~ .(round(mean(df$Adjusted_Score))) ~ N/cm^2))) +
 #  geom_vline(xintercept = mean(df$aveST), linetype = "dashed", color = "black") +  # Vertical line for green average
 #  geom_vline(xintercept = mean(df$Adjusted_Score), linetype = "dashed", color = "darkgrey") +
 #  theme_pubr() +
 #  labs(
 #    y = "Author",
 #    x = expression("Specific tension "~(N/cm^2)),
 #    color = " "
 #  )+
 #  theme(legend.position = "bottom")
 # 
 #  
 #  
 # saveFig(ST_change2,'Fig8 unweighted_weighted',8,15)

```

